version: '3'

services:
  kamailio:
    build:
      context: ./kamailio/docker
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - ./kamailio/config:/etc/kamailio
    environment:
      - DBHOST=127.0.0.1
      - DBNAME=kamailio
      - DBRWUSER=kamailio
      - DBRWPW=kamailiorw
      - DBROUSER=kamailioro
      - DBROPW=kamailioro
      - DBROOTUSER=root
      - RTPENGINE=rtpengine
      - RTPPROXY_SOCK=/var/run/rtpengine/rtpengine.sock
      - RTPEXTRAS=--no-log
    depends_on:
      - mariadb
      - phpmyadmin
      - rtpengine
    command: kamailio -f /etc/kamailio/kamailio.cfg -DD -E

  rtpengine:
    build:
      context: ./rtpengine/docker
      dockerfile: Dockerfile
    privileged: true
    network_mode: "host"
    volumes:
      - ./rtpengine/config/rtpengine.conf:/etc/rtpengine/rtpengine.conf
      - ./rtpengine/recordings:/var/spool/rtpengine/recordings

  mariadb:
    image: mariadb:latest
    network_mode: "host"
    volumes:
      - ./db/config:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=kamailio
      - MYSQL_USER=kamailio
      - MYSQL_PASSWORD=kamailiopw

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    network_mode: "host"
    environment:
      - PMA_HOST=127.0.0.1
    depends_on:
      - mariadb
